# Generated by Django 6.1 on 2026-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
