# Generated by Django 6.1 on 2026-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_activitylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('password_change_request', 'Password Change Request'), ('password_change', 'Password change'), ('notification_update', 'Notification Settings Update'), ('other', 'Other')], default='other'),
        ),
    ]
