# Generated by Django 6.1 on 2026-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecategory',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
