# Generated by Django 6.1 on 2026-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('low', 'Low priority'), ('medium', 'Medium priority'), ('high', 'High priority')], default='medium'),
        ),
    ]
