# Generated by Django 6.1 on 2026-09-04 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('company', models.CharField(max_length=64)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('social', 'Social Media'), ('email', 'Email'), ('other', 'Other')], default='website')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost'), ('junk', 'Junk / Spam')], default='new')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
