# Generated by Django 6.1 on 2026-09-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='expected_cloe_data',
            new_name='expected_close_date',
        ),
    ]
