# Generated by Django 6.1 on 2026-09-08 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField()),
                ('message', models.CharField()),
                ('type', models.CharField(choices=[('new_lead', 'New Lead'), ('new_contact', 'New Contact'), ('new_customer', 'New Customer'), ('new_deal', 'New Deal'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost')])),
                ('is_read', models.BooleanField(default=False)),
                ('source_type', models.CharField()),
                ('source_id', models.UUIDField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('push_notification', models.BooleanField(default=True)),
                ('lead_update', models.BooleanField(default=True)),
                ('contact_update', models.BooleanField(default=True)),
                ('customer_update', models.BooleanField(default=True)),
                ('deal_update', models.BooleanField(default=True)),
                ('activity_update', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
