# Generated by Django 6.1 on 2026-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
