# Generated by Django 6.1 on 2026-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_source_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='activity_update',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='contact_update',
            new_name='deal_lost',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='customer_update',
            new_name='deal_won',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='deal_update',
            new_name='new_contact',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='lead_update',
            new_name='new_customer',
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_deal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='new_lead',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('new_contact', 'New Contact'), ('new_customer', 'New Customer'), ('new_deal', 'New Deal'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('activity', 'Activity')]),
        ),
    ]
