# Generated by Django 6.1 on 2026-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_activity_update_notificationsettings_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='push_notification',
            field=models.BooleanField(default=True, help_text='represent all notifications'),
        ),
    ]
